version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: practice_postgres
    restart: always
    environment:
      POSTGRES_USER: practice_user
      POSTGRES_PASSWORD: practice_password
      POSTGRES_DB: practice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
